### ISSUE TITLE
Update Release Notes format

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#3215]
## Background

New requirements for the release process manifest itself in a separate step for release notes assessment and this places requirements on the content and verification process of the release notes as well. The release note expects certain things to be listed (e.g. known issues/missing functionality, changes since last release, etc...) and to be verified for example by a spell checker.

## Task breakdown

- [x] Assess the new content requirements (see the Release Notes assessment on the Release Process confluence page) and update the Release Notes format. Basically, create an example based on the [previous release](https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.23.0).
- [ ] Assess the procedural requirements (see the Release Notes assessment on the Release Process confluence page)
- [x] Write a release notes generator script to comply with both requirements and add it to the Mbed TLS project on github (the main input to the script is the ChangeLog file from the release)
- [ ] Confirm with @laumor01  and @daverodgman that the resulting release notes and checks are compliant with the requirements (and please keep me (@yanesca) in the loop as well)

**Comment by yanesca** [comment]
I have updated the task description to reflect recent changes.

**Comment by yanesca** [comment]
We have been following the new release process without any complaints for years, therefore we can consider our current process and release notes format satisfactory.
