### ISSUE TITLE
Add OoB testing to the release process

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#3222]
## Background

One of the new requirements against the release process is out of the box testing. We want to add a minimal (minimal in the sense that it satisfies process requirements) OoB testing to the release process and possibly improve it later if we see an opportunity to get more value for the end user out of it.

The minimal OoB testing could involve actions like:

- Go through the readme and verify that the versions of tools referred to are either tested in our CI or locally in their own environment.
- Check the readme and other docs "hang together"? i.e. check for broken links, obvious grammatical errors, out of date info.

## Task Breakdown

- [ ] Assess the OoB testing requirements (see the "Out of the Box testing review" on the Release Process confluence page), make a plan for OoB testing and document it in confluence (create a new child page for the release process)
- [ ] Consult PEG and find out how much time they need for their OoB testing if they choose to do it. Agree on hard time limits regarding their response, after which we can go on with the release in case they don't reply or are not ready. Capture the agreement in confluence.
- [ ] Consult PEG and find out how exactly they do their own OoB testing and document it in confluence.
- [ ] Design an OoB test plan that would reduce the risk of failing PEG's OoB test and satisfies the process requirements for OoB test review, upload it to confluence.
- [ ] Test the OoB test plan by performing it and confirming that the resulting documentation is enough to pass the OoB review (discuss it with @laumor01 and @daverodgman and please keep me (@yanesca) in the loop as well)

**Comment by yanesca** [comment]
@gilles-peskine-arm started a thread on the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls) discussing the minimum tool versions ("Development environment: minimum tool versions"). This task should take into account the outcome of that conversation.

**Comment by yanesca** [comment]
I have updated the task description to reflect recent changes.

**Comment by yanesca** [comment]
We have been following the new release process without any complaints for years, therefore we can consider our current process and  extent of OoB testing satisfactory.
