### ISSUE TITLE
Archive the old Mbed TLS website

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#4087]
## Background

Since early 2020, the Mbed TLS website is not the primary source for getting Mbed TLS and the newest announcements and documentation have moved to the TF.org mailing lists and wiki. The forum has been disabled years ago and today those discussions take place on the TF.org mailing lists as well.

The website does not serve the functions it used to and it is time to retire it.

## Task Breakdown

- [ ] Create an archive branch in the repository based on current master
- [ ] Dump the database and add it to the archive branch
- [ ] Add a section to the main readme on the archive branch describing where the dump is and how to restore the database
- [x] Capture the site with a web crawler (eg. wget) and replace the website on the master branch with this snapshot
- [x] Remove traces of interactive elements from the website (on master) - eg login page
- [ ] Redo the above two steps with Yuto's scripts to get the updates that happened since then
- [ ] Fix the link on the contact page (leads to the announcement list instead of the developer one)
- [ ] Make the site on the master branch live

**Comment by mpg** [comment]
>     * Remove traces of interactive elements from the website

Currently each page has a footer that reads "Want to stay up to date? To sign up for Mbed TLS news, log in to or create an Mbed account and update your marketing preferences." where we should be pointing the the -announce mailing list instead.

(I'm sure there are many others, but I just noticed that one and wanted to make sure it's recorded.)

**Comment by yutotakano** [comment]
I've self-assigned myself and will tackle the archival. As a side note, I think #3256 is a duplicate of this issue.

**Comment by yanesca** [comment]
The goal of this task was to serve as a transition step towards retiring the website and moving to readthedocs. Since the website has been closed down and readthedocs is up and running, we don't need this anymore.
