### ISSUE TITLE
Driver-only ECC: EPIC wrap-up

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7273]
At the end of the EPIC:

- [x] review and possibly update `docs/architecture/psa-migration/strategy.md` regarding this work - done in #7330 (hashes EPIC, but I couldn't help doing both at once).
- [x] consider updating the documentation for related options in `mbedtls_config.h`, for example `USE_PSA_CRYPTO` and `ECP_RESTARTABLE`
- [x] take one more look at all dependencies regarding PK, X.509 and TLS to ensure consitency
