### ISSUE TITLE
Code Size: aes.c: Investigate merging of similar functions

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [Mbed-TLS/mbedtls#7397]
Within `aes.c`, `mbedtls_internal_aes_encrypt()` and `mbedtls_internal_aes_decrypt()` are very similar.

This ticket is to investigate if it is worth merging the two into a single parameterised function.

Outputs will include code size savings but also performance impact on Cortex-M0, Cortex-M4, as well as AAarch64 and X64_64 CPUs.

Definition of done: a PR merged with code size improvements and known and accepted performance implications, or no PR but with justification (including what the code size savings and performance implications would have been).

**Comment by gilles-peskine-arm** [comment]
My hunch would be to factor common parts into `static` auxiliary functions, and then let the compiler inline them when optimizing for speed and not inline when optimizing for side.

**Comment by yanrayw** [comment]
> My hunch would be to factor common parts into `static` auxiliary functions, and then let the compiler inline them when optimizing for speed and not inline when optimizing for side.

The code structure is like this for now:
```
int mbedtls_internal_aes_encrypt(){
    COMMON_CODE
    ENCRYPT_CODE
    COMMON_CODE
}

int mbedtls_internal_aes_decrypt(){
    COMMON_CODE
    DECRYPT_CODE
    COMMON_CODE
}
```

After merging common parts, it should be
```
int ENCRYPT_FUNC(){
    ENCRYPT_CODE
}

int DECRYPT_FUNC(){
    DECRYPT_CODE
}

static int mbedtls_internal_aes_crypt(){
    COMMON_CODE
    if(ENCRYPT_MODE){
        ENCRYPT_FUNC
    } else {
        DECRYPT_FUNC
    }
    COMMON_CODE
}
```
Is this something in your mind? @gilles-peskine-arm .
More specifically, it looks we could change `mbedtls_internal_aes_encrypt` and `mbedtls_internal_aes_decrypt` to static functions like `mbedtls_internal_aes_crypt` here. May I ask What are the benefits of keeping both of them `non-static`?

**Comment by tom-cosgrove-arm** [comment]
I don't think we can make `mbedtls_internal_aes_encrypt` and `mbedtls_internal_aes_decrypt` `static`, as they appear to be part of the `MBEDTLS_AES_ENCRYPT_ALT` interface

**Comment by yanrayw** [comment]
I got an initial try. After [splitting common code into two functions](https://github.com/yanrayw/mbedtls/commit/0e5f88425e1d959b44860eef7f8ae406d916d25d), I found the code size for `aes.o` is even increased. (Measured on `x86` `ubuntu-18.04` with `GCC`). 

| GCC(8.4.0) | File Name | Old Size | New Size | Change (Bytes) |
| ---: | ---: | ---: |  ---: |  ---: |
| ca4ca9a | aes.o | 13449 | 13761 | +312 |

**Comment by yanrayw** [comment]
There is an alternative solution. I move [uncommon code into two difference functions](https://github.com/yanrayw/mbedtls/commit/270afe3c42e06093de9edae4a419162434d003ac). The code size for `aes.o` is improved. (Measured on `x86` `ubuntu-18.04` with `GCC`). 

| GCC(8.4.0) | File Name | Old Size | New Size | Change (Bytes) |
| ---: | ---: | ---: |  ---: |  ---: |
| ca4ca9a | aes.o | 13449 | 13297 | -152 |

The problem of this design is it breaks `MBEDTLS_AES_ENCRYPT_ALT` and `MBEDTLS_AES_DECRYPT_ALT` interface. As we only expose one cryption function to be overwritten by user. `mbedtls_internal_aes_encryption`  and `mbedtls_internal_aes_decryption` cannot be used as interface directly.

**Comment by gilles-peskine-arm** [comment]
Having looked at the code, the common header and common footer are very small: just xoring 16 bytes and incrementing a pointer. It's spelled out verbosely in the code to avoid dealing with endianness but the compiler doesn't care about that. So now I'm not surprised that it's a tiny amount of code, so the split approach doesn't help.

I don't see a way to make the different-cores approach work (unless we do that only when neither function has an ALT, which is more maintenance).

One use of `MBEDTLS_AES_DECRYPT_ALT` is to replace `mbedtls_internal_aes_decrypt` with a no-op function, for builds that don't need decryption and want to save code size. This isn't documented in any official place. It would be worth writing a guide (knowledge base entry, maybe with a link in the documentation of `MBEDTLS_AES_C`?) or adding maybe even an official build option.

**Comment by tom-cosgrove-arm** [comment]
@ronald-cron-arm You had some thoughts around this - anything you think that we're missing here?

**Comment by gilles-peskine-arm** [comment]
@yanrayw Some block cipher modes (GCM, CCM, CTR, …) use AES itself only in the encrypt direction, even when decrypting. For example AES-CTR-decrypt calls AES-encrypt, not AES-decrypt. Other modes (ECB, CBC, …) use AES-encrypt to encrypt and AES-decrypt to decrypt.

So users who only want CTR-like modes don't need the AES-decrypt function. But you can't express that in the legacy (non-PSA) API, because ECB is always enabled. With `MBEDTLS_PSA_CRYPTO_CONFIG`, users can express “I only want AES-CTR and AES-GCM” (which implies that AES-decrypt is not needed), but currently there's no way to transmit this information to the AES module.

**Comment by yanrayw** [comment]
Because we can't merge common code into common function for `mbedtls_internal_aes_encrypt()` and `mbedtls_internal_aes_decrypt()`. I plan to add a config option to enable a no-op `mbedtls_internal_aes_decrypt` function.

**TODO**:
- [ ] config option to enable a no-op decryption function in AES
- [ ] auto-enable the config option based on AES block cipher modes in PSA
- [ ] test case in `all.sh` (might need a new psa config file, might have to add dependency for test cases using ECB, CBC, KW)
- [ ] To be decided

**Comment by yanrayw** [comment]
I found the implementation of a no-op decryption function in https://github.com/Mbed-TLS/mbedtls/issues/7397#issuecomment-1547457204 could be linked to issue #7376 . It looks it's out of scope for Q2.

**Comment by yanrayw** [comment]
The implementation of a no-op AES decryption function is linked to #7367 .

I'll close this issue with below **conclusion**: 
We can't merge common code between `mbedtls_internal_aes_encrypt()` and `mbedtls_internal_aes_decrypt()` by either [approach 1](https://github.com/Mbed-TLS/mbedtls/issues/7397#issuecomment-1538128123) or [approach 2](https://github.com/Mbed-TLS/mbedtls/issues/7397#issuecomment-1538139738). 
 - The approach 1 increases code size as common header and common footer are very small.
 - The approach 2 breaks our `MBEDTLS_AES_ENCRYPT_ALT` and `MBEDTLS_AES_DECRYPT_ALT` interface.
