### ISSUE TITLE
Remove all deprecated items

### ISSUE THREAD

**Issue by daverodgman** [Mbed-TLS/mbedtls#8138]
As per https://github.com/Mbed-TLS/mbedtls/issues/6792#issuecomment-1531159865

- [x]     mbedtls_asn1_free_named_data() -> use mbedtls_asn1_free_named_data_list() or mbedtls_asn1_free_named_data_list_shallow() instead: https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/372
- [x] `mbedtls_asn1_write_algorithm_identifier()` → use `mbedtls_asn1_write_algorithm_identifier_ext()` instead: https://github.com/Mbed-TLS/mbedtls/issues/7963
- [x]     `MBEDTLS_PSA_CRYPTO_SE_C` → use the unified driver interface instead https://github.com/Mbed-TLS/mbedtls/issues/8151
- [x]     MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT -> let's only support the standard version: https://github.com/Mbed-TLS/mbedtls/pull/10298
- [x]     compat-2.x.h -> just remove #10133
- [x]     mbedtls_ssl_conf_curves() -> use mbedtls_ssl_conf_groups() instead - https://github.com/Mbed-TLS/mbedtls/issues/9891
- [x]     mbedtls_ssl_conf_max/min_version() -> use mbedtls_ssl_conf_max/min_tls_version() instead: https://github.com/Mbed-TLS/mbedtls/pull/10298
- [x]     mbedtls_x509write_crt_set_serial() -> use mbedtls_x509write_crt_set_serial_raw() instead - https://github.com/Mbed-TLS/mbedtls/issues/9892
 
Also:

- [x]     review after release of 3.6 LTS for any other deprecations not mentioned above

Already private, so can be removed after 1.0.4.0:

- [ ]     mbedtls_cipher_setup_psa() -> let's see how that evolves with driver-only ciphers work
- [ ]  mbedtls_pkcs5_pbkdf2_hmac() -> use mbedtls_pkcs5_pbkdf2_hmac_ext() instead (of the PSA Crypto API)

**Comment by mpg** [comment]
> review after release of 3.6 LTS for any other deprecations not mentioned above

Note: some functions* use `MBEDTLS_DEPRECATED` but not `\deprecated` (and perhaps the other way round happens as well), so we should be careful to use multiple methods when looking for deprecated items.

* I'm thinking about `mbedtls_ssl_conf_sig_hashes()` here. Done: https://github.com/Mbed-TLS/mbedtls/pull/10298

**Comment by mpg** [comment]
The pre-.0 part has been done, and I've filed separate issues for the post-.0 parts: https://github.com/Mbed-TLS/mbedtls/issues/10429 and https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/486
